FROM node:18-alpine as build
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./

# Fix permission on Vite binary
RUN chmod +x ./node_modules/.bin/vite

# Pass the backend API URL at build time via ARG
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
